### ISSUE TITLE
Test the build before releasing distribution

### ISSUE THREAD

**Issue by rockchalkwushock** [rockchalkwushock/how-to-open-source#15]
After reading through the discussion from [#2358](https://github.com/reactjs/redux/pull/2358) in `redux` I want to add a testing phase on the bundled code **after** the build has been output. This will address:

- _no changes from bundling break the expected result of the code_.
- _give assurance that the bundled code for release **does** work as expected_.

I know from prior poking around that [`glamorous`](https://github.com/paypal/glamorous) does this so I will look at how that team approached this as well as how [`redux`](https://github.com/reactjs/redux) handles it.

## Todo ✅ 

- [x] Research how to execute testing on build output.
- [x] Write tests for the output code.
- [ ] Write documentation on this case for other user's in #4
