### ISSUE TITLE
Migrate library bundling to rollup

### ISSUE THREAD

**Issue by rockchalkwushock** [rockchalkwushock/how-to-open-source#3]
This is not something that really must be done; you can bundle your library with `webpack` or `rollup`. I have decided to migrate this _very tiny_ library (_can you call it a library?_) to `rollup`.

## TODO

- [x] ~Remove `webpack` & corresponding packages/files.~
- [x] Add `rollup` & corresponding packages.
- [x] Create `rollup.config`.
- [x] Update scripts.
- [x] ~Take notes on process & how to make the migration to `rollup`.~ _Moved to #8_
- [x] ~Add to wiki~ _refer to #4_

## Update

~I will leave the `webpack` build and related packages/configs for people to refer too. There will be specific scripts for running the `webpack` build done through `nps`; but the distribution to the `npm` registry will be handled by `rollup`.~

**Comment by rockchalkwushock** [comment]
Follow example [here](https://github.com/rockchalkwushock/rollup-playground).
