### ISSUE TITLE
Migrate to nps

### ISSUE THREAD

**Issue by rockchalkwushock** [rockchalkwushock/how-to-open-source#7]
After wondering what `nps` was in the [`glamorous`](https://github.com/paypal/glamorous) package I checked it out and :raised_hands: **WOAH** :raised_hands: totally going to use this to better manage the npm scripts and cut down on the bloat in the `package.json`.

## TODO

- [x] Add [`nps`](https://github.com/kentcdodds/nps) & [`nps-utils`](https://github.com/kentcdodds/nps-utils). 
- [x] Create `package-scripts.js` or `package-scripts.yml`. :memo:
- [x] Migrate npm scripts from `package.json`.
- [x] Update scripts in `travis.yml`.

**Comment by rockchalkwushock** [comment]
Follow examples [here](https://github.com/rockchalkwushock/rollup-playground).
